{{- if .Values.PersistentVolumeClaim.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    cattle.io/creator: norman
  name: {{ .Values.PersistentVolumeClaim.name }}
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.PersistentVolumeClaim.resources.requests.storage }}
  storageClassName: {{ .Values.PersistentVolumeClaim.storageClassName }}
  volumeMode: Filesystem
{{- end }}
