apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.Role.name }}-{{ .Values.scope }}
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups:
        - ""
    resources:
      - pods
      - serviceaccounts
      - services
      - configmaps
      - secrets
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
