apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.RoleBinding.name }}-{{ .Values.scope }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.Role.name }}-{{ .Values.scope }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.ServiceAccount.name }}-{{ .Values.scope }}
  namespace: {{ .Values.namespace }}

