kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.Harbor.imagePullSecrets }}
  namespace: {{ .Values.namespace }}
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJ1c3RyLWhhcmJvci0xLm5hLnVpcy51bmlzeXMuY29tIjogewoJCQkiYXV0aCI6ICJjbTlpYjNRa2MyVnlkbWxqWlMxcGJuUmxiR3hwWjJWdVkyVXJjMmxmWW5WcGJHUTZNV0pSZDNOeVNGQjNNMjF0ZUdGSFRFTnlkMGRzTWs5MGMxRlRTM0JPYW5vPSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
