apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.Service.metadata.name }}-{{ .Values.scope }}
  namespace: {{ .Values.namespace }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: notebook
    port: 30503
    protocol: TCP
    nodePort: {{ .Values.Service.spec.ports.notebook.nodePort }}
    targetPort: 30503
  - name: sparkui
    port: 4040
    protocol: TCP
    targetPort: 4040
  selector:
    notebook-name: {{ .Values.Deployment.metadata.labels.notebookname }}-{{ .Values.scope }}
  sessionAffinity: None
  type: NodePort
